# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - .:/var/www/angular2restfulservice
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
